### ISSUE TITLE
Unit Tests: Each function exported should be wrapped in its own describe

### ISSUE THREAD

**Issue by kennylavender** [poetapp/poet-js#158]
We have an issue where a single describe method contains all the tests for a file.

- https://github.com/poetapp/poet-js/blob/master/src/Interfaces.test.ts
- https://github.com/poetapp/poet-js/blob/master/src/Claim.test.ts

I have not checked the other test files yet.

It's better if each function exported from a file has its own describe method. It makes it easier to read the tests and keep them separated. In the Interfaces test file, we already have an issue where it isIdentity is injected between isClaim tests.

**Comment by krobi64** [comment]
This is complete.
