### ISSUE TITLE
Sync package.json version with release version

### ISSUE THREAD

**Issue by geoffturk** [poetapp/poet-js#189]
Current release is 5.0.7 but package.json still shows 1.1.0.

@WesleyCharlesBlake @warrenv Is this a missed setting for the semver setup?

**Comment by warrenv** [comment]
I believe @wzalazar said this field does not get updated by semantic release. I'll look into it some more.

**Comment by wzalazar** [comment]
@warrenv it's possible to sync the version of `package.json` when we launch a new version. I tested it last week. We have to create a file called `.releaserc.json`

```
{
  "verifyConditions": ["@semantic-release/npm", "@semantic-release/git"],
  "prepare": [
    "@semantic-release/npm",
    {
      "path": "@semantic-release/git",
      "assets": ["package.json", "package-lock.json"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }
  ],
  "publish": ["@semantic-release/npm", "@semantic-release/github"]
}
```

also, you need to install as local dependencies these packages

```
npm run i --save-dev @semantic-release/git
npm run i --save-dev @semantic-release/github
npm run i --save-dev @semantic-release/npm
```
