### ISSUE TITLE
Create new module `createAuthorFromPrivateKey`

### ISSUE THREAD

**Issue by geoffturk** [poetapp/poet-js#197]
See: https://github.com/poetapp/documentation/blob/master/rdd/separate-file-uploads.md

**Comment by krobi64** [comment]
Why are we modifying author?

**Comment by geoffturk** [comment]
@kennylavender ^^^^^^^^^^^^^^

**Comment by kennylavender** [comment]
Discussed with @krobi64, I had a misunderstanding of what the author/issuer is going to be for users claims. This is not needed. @krobi64 is going to update the document.
