### ISSUE TITLE
Semantic release is Failing 

### ISSUE THREAD

**Issue by wzalazar** [poetapp/poet-js#209]
The task is not working properly now

https://travis-ci.org/poetapp/poet-js/jobs/44836890

![screen shot 2018-10-30 at 12 44 13](https://user-images.githubusercontent.com/5795257/47730793-a8eeb000-dc41-11e8-9064-32a3602d301c.png)

**Comment by geoffturk** [comment]
@warrenv @WesleyCharlesBlake Do either of you have an idea what is causing this to fail?

**Comment by WesleyCharlesBlake** [comment]
this seems like a Github protected branches issue.

```remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "continuous-integration/travis-ci" is expected. At least 1 approving review is required by reviewers with write access.   ```

semantic-releases creates a github tag and release on master, but the user as authed by the GH_TOKEN is not able to write to master due to the protected branches. Are we using the poet-ci GH user as per node and frost-api?

**Comment by wzalazar** [comment]
@WesleyCharlesBlake I think we need to add this option

![screen shot 2018-10-31 at 09 30 28](https://user-images.githubusercontent.com/5795257/47788178-b6627380-dcef-11e8-9ece-45a77646ade9.png)

**Comment by WesleyCharlesBlake** [comment]
I see that for some reason the GH_TOKEN appears to have different perms compared to those created with the semantic-release-cli tool.

Im recreating new tokens now and will see if this resolves the issue, as it still points to a permission issue on GitHub for the poet-ci user

**Comment by WesleyCharlesBlake** [comment]
I think I have this issue figured out.
![Uploading Screenshot from 2018-10-31 16-37-12.png…]()

Only the Quality Engineering user is an admin of poet-js. the `poet-ci` user required to run semantic-release is thus treated like a non admin user, and has to adhere to the reviews and status checks requirement on the repo.

I will add poet-ci to the QE group, and re-test. this should resolve this issue.

**Comment by WesleyCharlesBlake** [comment]
OK, semantic-releases are fixed now!

https://travis-ci.org/poetapp/poet-js/builds/448888018
