### ISSUE TITLE
Secure HTML entities

### ISSUE THREAD

**Issue by wzalazar** [poetapp/poet-js#41]
With the goal to protect us over XXS attacks, we have to sanitize the data in all `JSON.stringify`

I found this library: https://github.com/yahoo/serialize-javascript

**Comment by wzalazar** [comment]
@geoffturk 

We decided doesn't need, because there is only one call an Insight and this we will remove it in the near future and doesn't represent a risk at moment.

**Comment by geoffturk** [comment]
OK. Thanks, Walter.
