### ISSUE TITLE
Stop using bitcore-lib for crypto

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/poet-js#51]
We have three functions that depend on bitcore-lib to perform cryptography:

https://github.com/poetapp/poet-js/blob/63fd08f1bccde1cec980178d3aaa8e0a9362ecf3/src/Claim.ts#L25-L37

https://github.com/poetapp/poet-js/blob/63fd08f1bccde1cec980178d3aaa8e0a9362ecf3/src/Claim.ts#L25-L37

https://github.com/poetapp/poet-js/blob/63fd08f1bccde1cec980178d3aaa8e0a9362ecf3/src/Claim.ts#L51-L59

We're currently using [bitecore-lib's ECDSA](https://github.com/bitpay/bitcore-lib/blob/1186be59dc60a796df47793251246e731a513bbe/lib/crypto/ecdsa.js) functions which were originally written by @ryanxcharles

He has a [more recent version and better maintained](https://github.com/yoursnetwork/yours-bitcoin/blob/8ca98c31a72676b45d46305959835713c6de0c5d/lib/ecdsa.js) which is inspired in part by [bitcoin-js](https://github.com/bitcoinjs/bitcoinjs-lib) .

We could also try using [NodeJS' crypto APIs](https://nodejs.org/api/crypto.html), since we don't really need the claim's signatures to be bitcoin-compatible, but that could prove hard would would also make it harder to make poet-js compatible with non-nodejs environments in the future.

I'd start by trying with bitcoin-js, since we'll probably need it to parse transactions anyways.

**Comment by geoffturk** [comment]
needed-by poetapp/node#24

**Comment by lautarodragan** [comment]
@geoffturk it's not really really needed for that one though. We could keep using it for the crypto part that isn't bitcoin related.

**Comment by geoffturk** [comment]
OK. I will de-link then. Thanks for the heads up.

**Comment by lautarodragan** [comment]
@krobi64 is this one addressed by JSON-LD?

**Comment by geoffturk** [comment]
@krobi64 Lautaro and I discussed this one yesterday. In summary, we do want to get rid of bitcore-lib and replace it either with bitcoinjs-lib or some native node crypto library. I think bitcoinjs-lib is probably a good option because it is well-maintained.

**Comment by warrenv** [comment]
:+1:
bitcore-lib is also the source of some of outstanding  snyk vulnerabilities.

**Comment by krobi64** [comment]
Done.
