### ISSUE TITLE
Improve isClaim

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/poet-js#85]
https://github.com/poetapp/poet-js/blob/6bcf2205638d3543d6f6801ad58c9ac2f3d248a0/src/Interfaces.ts#L12-L22

Avoid using `instanceof`.

Maybe use Joi?

A quick fix to avoid using `instanceof` could be changing `object.dateCreated instanceof Date` to `!isNaN(new Date(object.dateCreated))`. 

We should probably separate the logic that checks whether something is a date to a `isDate(something: any): something is Date` function.

```ts
 export const isClaim = (something: any): something is Claim =>
     !!something &&
     typeof something === 'object' &&
     something.id && 
     something.publicKey && 
     something.signature && 
     something.type && 
     something.attributes && 
     isDate(something.dateCreated)

// somewhere else
export const isDate = (something: any): something is Date =>
  typeof something == 'object' && !isNaN(new Date(something))
```

This is just an example, I'm not sure this example implementation of `isDate` works as it should.

We should unit test `isDate` too.

**Comment by lautarodragan** [comment]
@geoffturk do we have a milestone for after mainnet? I don't think we need to address this for mainnet at all

**Comment by krobi64** [comment]
This is done using Joi in poet-js 5.x @lautarodragan does this meet your criteria?

**Comment by geoffturk** [comment]
Ping @lautarodragan 

Can we close this one?

**Comment by lautarodragan** [comment]
@geoffturk @krobi64 it does!
